version: '3'

services:
  database:
    image: mysql
    container_name: cfs_php_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

  db_admin:
    image: phpmyadmin/phpmyadmin:5
    container_name: cfs_php_myadmin
    ports:
      - '${MYADMIN_PORT}:80'
    environment:
      - PMA_HOST=database
      - PMA_ABSOLUTE_URI=http://localhost:${MYADMIN_PORT}/
    depends_on:
      - database
    volumes:
      - db_admin_data:/var/www/html

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: cfs_php_web
    ports:
      - '${WEB_PORT}:80'
    working_dir: /var/www/
    volumes:
      - .:/var/www/
      - ./public:/var/www/html
    depends_on:
      - database

volumes:
  db_data:
  db_admin_data: